spring:
  application:
    name: zoj-backend-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.128:8848
        username: 
        password: 
        prefer-ip-address: true
    gateway:
      routes:
        - id: zoj-backend-user-service
          uri: lb://zoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: zoj-backend-question-submit-service
          uri: lb://zoj-backend-question-service
          predicates:
            - Path=/api/question_submit/**
          filters:
            - RewritePath=/api/question_submit/(?<segment>.*), /api/question/question_submit/$\{segment}
        - id: zoj-backend-question-service
          uri: lb://zoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: zoj-backend-judge-service
          uri: lb://zoj-backend-judge-service
          predicates:
            - Path=/api/judge/**

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      # 自动发现服务
      group-name: "微服务接口文档"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

server:
  port: 8100