server:
  port: 8102
  servlet:
    context-path: /api/question

spring:
  application:
    name: zoj-backend-question-service
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.213.128
    port: 5672
    username: itheima
    password: 123321
    virtual-host: /
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.213.128:8848
        username: 
        password: 
        prefer-ip-address: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.213.128:3306/zoj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123
  data:
    redis:
      host: 192.168.213.128
      port: 6379
      database: 0
      timeout: 10000ms

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为0）
  type-aliases-package: com.zluolan.zojbackendmodel.entity

knife4j:
  enable: true
  production: false
  basic:
    enable: false

logging:
  level:
    com.zluolan.zojbackendquestionservice: debug